### ISSUE TITLE
Problem with pre-training

### ISSUE THREAD

**Issue by OvO1111** [ibrahimethemhamamci/GenerateCT#11] opened 2024-01-25 03:58 UTC
Hi there, thanks for your great work, I'm currently running into a problem while running `train_transformer.py`. After downloading the pretrained ct-vit model checkpoint and feeding it to the parameter `pretrained_cvivit_path` on [https://github.com/ibrahimethemhamamci/GenerateCT/blob/main/train_transformer.py#L58](url), I get `RuntimeError: Error(s) in loading state_dict for CTViT: Missing key(s) in state_dict: "vq._codebook.embed_avg".` on [https://github.com/ibrahimethemhamamci/GenerateCT/blob/main/transformer_maskgit/transformer_maskgit/ctvit.py#L406](url). I presume there is a problem about the checkpoint file `ctvit_pretrained.pt` ? Let me know if you have some idea about this error. Thanks in advance!

**Comment by sezginerr** [comment] 2024-02-10 01:14
It might be caused by vector_quantize_pytorch version mismatch. Can you try running `pip install vector-quantize-pytorch==1.1.2` in your current env? This version should be installed  in your env if you run `pip install -e` for transformer_maskgit though.

**Comment by sezginerr** [comment] 2024-05-19 12:20
I am closing this for now. Let us know if you have further question.

**Closed by sezginerr** 2024-05-19 12:20 UTC
